### PR TITLE
Update msg fields to include units

### PR DESCRIPTION
**Pull request by briellelaw**
The msg fields now include units for greater clarity.
These units reflect the data that is directly outputted from 
the sensors as noted in:
https://ubcsailbot.atlassian.net/wiki/spaces/ADA2/pages/506167525/CAN+Bus+Inputs+and+Outputs

Note: From what I've been told, the ais' gps is intended to be 
used as a backup. These fields are not currently being stored 
in the network table. Further investigation is required.

### CODE REVIEW

**Review by brucecui97 — APPROVED** [review]
awesome work. Thanks Brielle!

**Comment by briellelaw** [comment]
Updated the gps_timestamp units to indicate 'utc' standard - I think this is more clear and useful information

**Comment by briellelaw** [comment]
From Simon: some fields have more precision.
gps, gyroscope, accelerometer should be switched to float32

**Comment by briellelaw** [comment]
Clarification Needed:
gps lat and lon are actually received in 'degree, minutes, decimal minutes' convention.
Ie. Longitude (degree, minutes, decimal minutes DDMM.MMMMMMM)
Is this the form you want it in? The data has to be processed once received from the CANbus anyways, so I can separate it into degrees, minutes, and decimal minutes.

**Comment by derain12** [comment]
@brucecui97 Do you need to know the actual angular position of the winch itself (ie. how much of the rope is in)? The only "feedback" of the rigging is the Sailencoder (boom angle), but I can add a frame that reports the angular position reported by the winch motor.

**Comment by brucecui97** [comment]
> @brucecui97 Do you need to know the actual angular position of the winch itself (ie. how much of the rope is in)? The only "feedback" of the rigging is the Sailencoder (boom angle), but I can add a frame that reports the angular position reported by the winch motor.

good point, thanks for asking! I actually haven't thought too much about the low-level sail controller yet, but currently I think it's helpful to have both:
1. actual angular position of the winch itself (ie. how much of the rope is in)
2. Sailencoder (boom angle)

**Comment by derain12** [comment]
> > @brucecui97 Do you need to know the actual angular position of the winch itself (ie. how much of the rope is in)? The only "feedback" of the rigging is the Sailencoder (boom angle), but I can add a frame that reports the angular position reported by the winch motor.
> 
> good point, thanks for asking! I actually haven't thought too much about the low-level sail controller yet, but currently I think it's helpful to have both:
> 
> 1. actual angular position of the winch itself (ie. how much of the rope is in)
> 2. Sailencoder (boom angle)

Updated in [https://ubcsailbot.atlassian.net/wiki/spaces/ADA2/pages/506167525/CAN+Bus+Inputs+and+Outputs](url). @brucecui97 @briellelaw Please check updates for CAN IDs 0x50, 0x51, 0x53, 0x54.

**Comment by brucecui97** [comment]
Just curious can we merge this now?

**Comment by brucecui97** [comment]
> From Simon: some fields have more precision.
> gps, gyroscope, accelerometer should be switched to float32
> 
> gps lat/lon from float64 to float32?

I personally think let's be consistent and convert everything to float 32

**Comment by derain12** [comment]
> > From Simon: some fields have more precision.
> > gps, gyroscope, accelerometer should be switched to float32
> > gps lat/lon from float64 to float32?
> 
> I personally think let's be consistent and convert everything to float 32

Agreed, If anything, if we find the 32-bit precision to be insufficient (ie. with lat/long), we can always switch to float64

**Review by derain12 — APPROVED** [review]
Ready to merge for software testing. We can deal with float64/float32 debate later

**Comment by tylerlum** [comment]
1. Tbh not sure how the conversion works, but it sounds simple enough on either end, so choose whatever is easier.
2. Again, we just want to have the best most up to date values whenever we can. However we can best get that, just let us know. Sounds like the bool would make it easy to know for sure? Not sure when gps would be off.

**Comment by briellelaw** [comment]
alright, i'll modify all the relevant fields to be float32, 
will leave the lat/lon as degree-minutes,
and will add a bool for the gps state.

I'll make these minor changes and then merge it in by tonight.

**Comment by briellelaw** [comment]
> > > From Simon: some fields have more precision.
> > > gps, gyroscope, accelerometer should be switched to float32
> > > gps lat/lon from float64 to float32?
> > 
> > 
> > I personally think let's be consistent and convert everything to float 32
> 
> Agreed, If anything, if we find the 32-bit precision to be insufficient (ie. with lat/long), we can always switch to float64

I think I know why we had it as a float64 originally. To parse the data from the canbus, a float64 prevents any possibility of overflow since we are adding 2x 32bit integers. But i will do the intermediate computations with a float64, and store the result in a float32 for consistency.

**Comment by tylerlum** [comment]
Awesome thanks Brielle!

**Pull request merged**
